

import XCTest
@testable import gitRepositories

class RepositoriesTest: XCTestCase {
    

    func testRepositoriesKeys() {
        var respositoryKey = Repositories.CodingKeys(rawValue: "id")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "node_id")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "name")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "full_name")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "private")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "owner")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "html_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "description")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "fork")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "forks_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "keys_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "collaborators_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "teams_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "hooks_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "issue_events_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "events_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "assignees_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "branches_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "tags_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "blobs_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "git_tags_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "git_refs_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "trees_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "statuses_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "languages_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "stargazers_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "contributors_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "subscribers_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "subscription_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "commits_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "git_commits_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "comments_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "issue_comment_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "contents_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "compare_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "merges_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "archive_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "downloads_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "issues_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "pulls_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "milestones_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "notifications_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "labels_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "releases_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "deployments_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "created_at")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "updated_at")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "pushed_at")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "git_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "ssh_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "clone_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "svn_url")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "homepage")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "size")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "stargazers_count")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "watchers_count")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "language")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "has_issues")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "has_projects")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "has_downloads")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "has_wiki")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "has_pages")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "forks_count")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "archived")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "disabled")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "open_issues_count")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "license")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "forks")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "open_issues")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "watchers")
        XCTAssertNotNil(respositoryKey?.rawValue)
        respositoryKey = Repositories.CodingKeys(rawValue: "default_branch")
        XCTAssertNotNil(respositoryKey?.rawValue)
    }
    
 

    

}
